platformName: Android
#模拟器
platformVersion: 4.4.2
deviceName: 127.0.0.1:62001

# Galaxy S9
#platformVersion: 8.0.0
#deviceName: Galaxy S9testtest

appname: kaoyan3.1.0.apk
noReset: False
unicodeKeyboard: True
resetKeyboard: True
#
appPackage: com.tal.kaoyan
appActivity: com.tal.kaoyan.ui.activity.SplashActivity
ip: 127.0.0.1
port: 4723

# Honor Magic 2update
#platformVersion: 9.0
#deviceName: Honor Magic 2
#
#appname: kaoyan3.1.0.apk
#noReset: False
#nicodeKeyboard: True
#resetKeyboard: True
##
#appPackage: com.tal.kaoyan
#appActivity: com.tal.kaoyan.ui.activity.SplashActivity
##ip: 127.0.0.1
#port: 4723